### ISSUE TITLE
Move to JuliaCloud?

### ISSUE THREAD

**Issue by iamed2** [JuliaCloud/AWSS3.jl#33]
We're about to start using this to replace our use of AWSSDK for S3, so it would be nice to move this into the org, if you (@samoconnor) are okay with that.

**Comment by samoconnor** [comment]
Yes that makes sense (I won't have time to do it immediately).

**Comment by samoconnor** [comment]
xfer done
Are there any gotchas WRT to attobot? Pkg3?
@andreasnoack? @ararslan @KristofferC?

**Comment by KristofferC** [comment]
Think the url needs to be changed in METADATA.jl to tag new versions with Attobot.

**Comment by samoconnor** [comment]
@ararslan, I would like to move the following packages (depended on by AWSCore) into an Org so that other org members can push bug fixes if/when I'm not available (without being forced to fork).

https://github.com/samoconnor/XMLDict.jl (-> JuliaData?)
https://github.com/samoconnor/SymDict.jl (-> JuliaCollections?)
https://github.com/samoconnor/Retry.jl (-> JuliaIO?)

Can you suggest better homes? and/or add me as a member of relevant groups so I can do the transfers?

**Comment by iamed2** [comment]
SymDict can go into JuliaCollections and I'm a member of that.
Retry might make sense in JuliaWeb? Since it's mostly used for that sort of thing.
XMLDict in JuliaIO makes sense I think, as most of the data format packages are there (including LightXML).

**Comment by rofinn** [comment]
Made issues for moving other packages and closing
